services:
  db:
    image: postgres:15-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: price_tracker
      POSTGRES_PASSWORD: 87760081330
      POSTGRES_DB: db
    ports:
      - "5432:5432"
